'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowLeft, BookOpen, Feather, Layers } from 'lucide-react';
import posts from './posts.generated.json';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
const topics = ['全部文章', '学习笔记', '实践记录', '日常随笔'];
export default function Home() {
 const [topic,setTopic]=useState('全部文章'); const [slug,setSlug]=useState('');
 useEffect(()=>{const update=()=>{try{setSlug(decodeURIComponent(location.hash.slice(1)))}catch{setSlug('missing')}window.scrollTo(0,0)};update();window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
 const post=posts.find(p=>p.slug===slug);
 useEffect(()=>{document.title=post?`${post.title} · 拾页`:'拾页 · 学习手记'},[post]);
 return <><a className="skip" href="#content" onClick={(event)=>{event.preventDefault();document.getElementById("content")?.focus()}}>跳转到正文</a><header className="header"><a className="brand" href="#"><span className="brand-mark"><BookOpen size={22}/></span><strong>拾页<span>.</span></strong><span className="brand-sub">学习手记</span></a><nav aria-label="主导航"><a href="#" aria-current={!slug?'page':undefined}>文章</a><a href="#about" aria-current={slug==='about'?'page':undefined}>关于</a><span className="nav-note">保持好奇，慢慢生长 ↗</span></nav></header><main id="content" className="shell" tabIndex={-1}>
 {post?<article className="reading"><a className="back" href="#"><ArrowLeft size={16}/> 回到文章列表</a><div className="eyebrow">{post.category}{post.sample ? " / 示例文章" : ""}</div><h1>{post.title}</h1><p className="reading-desc">{post.description}</p><div className="meta">{post.date} · {post.minutes} 分钟阅读</div><div className="prose"><Markdown remarkPlugins={[remarkGfm]} skipHtml components={{table: ({children}) => <div className="table-scroll"><table>{children}</table></div>}}>{post.body}</Markdown></div><div className="article-end">写下来，是理解的开始。</div><a className="back" href="#"><ArrowLeft size={16}/> 继续读其他文章</a></article>
 :slug==='about'?<article className="reading"><a className="back" href="#"><ArrowLeft size={16}/> 回到文章列表</a><div className="eyebrow">ABOUT THIS NOTEBOOK</div><h1>给思考，留一页。</h1><div className="prose"><p>拾页是一本公开的学习手记。这里用来保存学过的知识、做过的小项目，以及生活里值得记住的片刻。</p><h2>在这里写些什么</h2><p>学习笔记：把复杂的概念拆开，用自己的话重新讲一遍。</p><p>实践记录：记下从想法到完成的过程，也留下踩过的坑。</p><p>日常随笔：读书、散步，和偶尔冒出来的念头。</p><h2>关于作者</h2><p>这里留给未来的自我介绍。你可以放上自己的名字、正在学习的方向，以及想分享这个网站的原因。</p><p className="sample-note">作者介绍待补充。</p></div></article>
 :slug?<article className="reading"><h1>这一页还没有写下。</h1><p>文章可能已更名，请回到列表继续阅读。</p><a className="back" href="#">返回文章列表</a></article>
 :<><section className="intro"><div><div className="eyebrow"><span className="status-dot"/> 一个持续更新的个人笔记本</div><h1>把学到的，<br/>变成<span className="underlined">自己的。</span></h1><p>记录学习的过程，也收集生活的切片。<br/>在输入与输出之间，让每一点思考都有迹可循。</p><a className="intro-link" href={posts.length ? `#${posts[0].slug}` : "#about"}>从一篇笔记开始 <ArrowUpRight size={18}/></a></div><aside className="margin-note"><span className="note-label">写在页边</span><p>不必等到完全理解，<br/>才开始记录。</p><div className="note-line"/><span>边学，边做，边写。</span><small>ON LEARNING & LIVING</small></aside></section><div className="content-grid"><div className="feed"><div className="section-heading"><h2>最近写下的</h2><span>{posts.length.toString().padStart(2,'0')} 篇文章</span></div><div className="tabs" aria-label="文章分类">{topics.map(t=><button key={t} className={t===topic?'active':''} aria-pressed={t===topic} onClick={()=>setTopic(t)}>{t}</button>)}</div><div>{!posts.some(p=>topic==='全部文章'||p.category===topic)&&<p className="empty-posts">这个分册还没有文章，下一篇见。</p>}{posts.filter(p=>topic==='全部文章'||p.category===topic).map((p,i)=><a href={`#${p.slug}`} className={`post-card ${i===0&&topic==='全部文章'?'featured':''}`} key={p.slug}><div className="post-top"><span className="category">{p.category}</span>{i===0&&topic==='全部文章'&&<span className="picked">精选笔记</span>}<time>{p.date}</time></div><h3>{p.title}<ArrowUpRight size={21}/></h3><p>{p.description}</p><div className="post-bottom"><div>{p.tags.map(t=><span key={t}>#{t}</span>)}</div><span>{p.minutes} 分钟阅读</span></div></a>)}</div><div className="list-end"><span/> 暂时写到这里，下一页见 <span/></div></div><aside className="sidebar"><section className="about-card"><div className="small-icon"><Feather size={21}/></div><h2>你好，欢迎翻开这一页。</h2><p>一个学习者的数字自留地。<br/>把知识整理成笔记，把想法付诸实践，也给日常留一点位置。</p><a href="#about">关于这个小站 <ArrowUpRight size={16}/></a></section><section className="topic-section"><h2><Layers size={17}/> 笔记分册</h2>{topics.slice(1).map((t,i)=><button key={t} onClick={()=>setTopic(t)}><span className={`topic-dot dot-${i}`}/><span>{t}<small>{['把知识串成自己的体系','从动手到真正理解','学习之外，也有生活'][i]}</small></span><span className="topic-count">{posts.filter(p=>p.category===t).length.toString().padStart(2,'0')}</span></button>)}</section><div className="side-foot"><span>✳</span><p>这是一座慢慢搭建的花园。<br/>不追赶更新，只认真记录。</p></div></aside></div></>}
 </main><footer><a className="footer-brand" href="#">拾页.</a><span>记录，是为了更好地出发。</span><span>© 2026 · 学习与生活的片段</span></footer></>;
}
